plugins:
  -
    - tabs
    - dedupeIds: true

themeConfig:
  sidebar: 
    - title: Getting Started
      path: /
    - title: Frameworks
      children:
        - title: Empty Group A
        - title: JSX
          children:
            - /frameworks/jsx/react
            - /frameworks/jsx/preact
        - title: non-JSX
          children:
            - /frameworks/non-jsx/vue.js
            - /frameworks/non-jsx/angular
        - title: Empty Group B
    - title: External
      children:
        - title: VuePress
          path: https://v1.vuepress.vuejs.org
    - title: Vue.js
      path: https://vuejs.org/v2/guide/
